### ISSUE TITLE
Fix bug that initiates an EIP-1559 tx instead of a CIP-64 tx since viem@1.180

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/txtypes#1]
### Before `viem@1.18.0`

The following code used to correctly generate a CIP-42 transaction (before [viem@1.18.0](https://github.com/wagmi-dev/viem/releases/tag/viem%401.18.0), with viem@1.16.0)

```ts
/**
 * Transaction type: 124 (0x7c)
 * Name: "Dynamic fee"
 * Description: Celo dynamic fee transaction (with custom fee currency)
 */
async function demoFeeCurrencyTransactionType() {
    console.log(`Initiating custom fee currency transaction...`);
    const transactionHash = await client.sendTransaction({
        account, // Sender
        to: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8", // Recipient (illustrative address)
        value: parseEther("0.01"), // 0.01 CELO
        feeCurrency: "0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1", // cUSD fee currency
        maxFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
        maxPriorityFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
    });

    const transactionReceipt = await publicClient.waitForTransactionReceipt({
        hash: await transactionHash,
    });

    printFormattedTransactionReceipt(transactionReceipt);
}
```

Example output: 

```sh
Initiating custom fee currency transaction...
Transaction details: {
  type: '0x7c',
  status: 'success',
  transactionHash: '0x9935c26499205b028a2518cfa5a32b7ebf68533deec414c8ded9f91ae5aa5dd8',
  from: '0x303c22e6ef01cba9d03259248863836cb91336d5',
  to: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  feeCurrency: undefined
} 
```

Transaction in [explorer](https://explorer.celo.org/alfajores/tx/0x9935c26499205b028a2518cfa5a32b7ebf68533deec414c8ded9f91ae5aa5dd8): 

<img width="796" alt="image" src="https://github.com/0xarthurxyz/txtypes/assets/46296830/bd20bf53-3ed6-41b4-88ed-be10e3abc766">

### After `viem@1.18.0`

Now the same code generates an EIP-1559 transaction and pays for gas in CELO and not cUSD.

```ts
/**
 * Transaction type: 123 (0x7b)
 * Name: "Dynamic fee"
 * Description: Celo dynamic fee transaction (with custom fee currency)
 */
async function demoFeeCurrencyTransactionType() {
    console.log(`Initiating custom fee currency transaction...`);
    const transactionHash = await client.sendTransaction({
        account, // Sender
        to: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8", // Recipient (illustrative address)
        value: parseEther("0.01"), // 0.01 CELO
        feeCurrency: "0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1", // cUSD fee currency
        maxFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
        maxPriorityFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
    });

    const transactionReceipt = await publicClient.waitForTransactionReceipt({
        hash: await transactionHash,
    });

    printFormattedTransactionReceipt(transactionReceipt);
}
```

Example output:

```sh
Initiating custom fee currency transaction...
Transaction details: {
  type: 'eip1559',
  status: 'success',
  transactionHash: '0xf58e2706c60b50f97cf8f9d6f50d2484b895dc79cf1fb26d82cf9c9b25abcf38',
  from: '0x303c22e6ef01cba9d03259248863836cb91336d5',
  to: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  feeCurrency: undefined
} 
```

Transaction in [explorer](https://explorer.celo.org/alfajores/tx/0xf58e2706c60b50f97cf8f9d6f50d2484b895dc79cf1fb26d82cf9c9b25abcf38): 

<img width="768" alt="image" src="https://github.com/0xarthurxyz/txtypes/assets/46296830/2e39c973-2cbe-4da9-a1a1-1645b74a4937">

### Expected

Code should generate a CIP-64 transaction (type: `0x7b`) and pay for gas in cUSD

### Checks

[Sender](https://explorer.celo.org/alfajores/address/0x303C22e6ef01CbA9d03259248863836CB91336D5/transactions#address-tabs) has sufficient CELO and cUSD to pay for gas in cUSD.

<img width="678" alt="image" src="https://github.com/0xarthurxyz/txtypes/assets/46296830/5308f716-61e4-47a5-a114-4ec0b594f936">

**Comment by nicolasbrugneaux** [comment]
(very early) wip 
- https://github.com/clabs-co/viem/pull/6

**Comment by arthurgousset** [comment]
When new version of `viem` is published:

- [x] upgrade `txtypes` package `viem` version
- [x] run demo to test
- [ ] copy/paste demo output into `README.md` (to replace current demo output)

**Comment by nicolasbrugneaux** [comment]
For tracking reasons, the new PR for the viem/wagmi team:
- https://github.com/wagmi-dev/viem/pull/1434

**Comment by nicolasbrugneaux** [comment]
@0xarthurxyz viem merged my PR and published a [1.18.6 version](https://github.com/wagmi-dev/viem/releases/tag/viem%401.18.6) with the fix

**Comment by arthurgousset** [comment]
## QA

Oddly enough, [`viem@1.18.6`](https://github.com/wagmi-dev/viem/blob/main/src/CHANGELOG.md#1186) does not seem to fix the regression. 

This is unexpected, because when we tested the viem PR that fixes the regression locally with @nicolasbrugneaux (using `yarn link`), the regression was fixed and the `demo.ts` produced a type `123` transaction. 

At the moment, both on [`viem@1.18.6`](https://github.com/wagmi-dev/viem/blob/main/src/CHANGELOG.md#1186) (regression fix) and `viem@1.18.8` (latest release), `demo.ts` produces a type `2` transaction when the `feeCurrency` parameter is specified. 

## Ideas

### Gas estimation

I'm not sure if it's relevant, but maybe I need to estimate gas better. This would be weird, because the way I specified gas (hard-coded values for `maxFeePerGas` and `maxPriorityFeePerGas`) hasn't changed between `viem@1.16` and `viem@1.18.0` onwards.

But in any case, I'm taking inspiration from here for a better way to estimate gas: 

- [docs.celo.org](https://docs.celo.org/developer/viem#gas-price)
  ```ts
  async function getGasPrice(client, feeCurrencyAddress?: Address) {
    const priceHex = await client.request({
      method: "eth_gasPrice",
      params: [feeCurrencyAddress],
    })
    return hexToBigInt(priceHex)
  }
  
  tx.maxFeePerGas = await getGasPrice(client, tx.feeCurrency)
  ```
- [ethcc-presentation demo](https://github.com/0xarthurxyz/ethcc-presentation/blob/78dcb2ee20e2d1ea85a59683a94e57af8a56a5b4/code/index.js#L92C1-L99C2)

  ```js
  // to make sure we pay the right price for gas in the right currency
  async function getGasPrice(client) {
    const priceHex = await client.request({
      method: "eth_gasPrice",
      params: [FEE_CURRENCIES_ALFAJORES["cusd"]],
    })
    return hexToBigInt(priceHex)
  }
  ```

- [valora-inc/wallet](https://github.com/valora-inc/wallet/blob/main/src/viem/estimateFeesPerGas.ts#L5)

  ```ts
  // Custom function for Celo that can be removed once it's supported in viem
  // See https://github.com/wagmi-dev/viem/discussions/914
  export async function estimateFeesPerGas(client: Client, feeCurrency?: Address) {
    // The gasPrice returned on Celo is already roughly 2x baseFeePerGas
    // so we can just use that as maxFeePerGas, no need for an explicit maxPriorityFeePerGas
    // See this interesting thread for more details:
    // https://valora-app.slack.com/archives/CNJ7KTHQU/p1697717100995909?thread_ts=1697647756.662059&cid=CNJ7KTHQU
    const gasPrice = await getGasPrice(client, feeCurrency)
    const maxFeePerGas = gasPrice
    // Here we still return maxPriorityFeePerGas as undefined to be consistent with viem
    // and so consumer TXs are correctly serialized as CIP-42 TXs
    // See https://github.com/wagmi-dev/viem/blob/5c95fafceffe7f399b5b5ee32119e2d78a0c8acd/src/chains/celo/serializers.ts#L105-L106
    return { maxFeePerGas, maxPriorityFeePerGas: undefined }
  }
  
  // Get gas price with optional fee currency, this is Celo specific
  // See https://docs.celo.org/developer/viem#gas-price
  export async function getGasPrice(client: Client, feeCurrency: Address | undefined) {
    const priceHex = await client.request({
      method: 'eth_gasPrice',
      ...((feeCurrency ? { params: [feeCurrency] } : {}) as object),
    })
    return hexToBigInt(priceHex)
  }
  ```

### Local build vs published build

When @nicolasbrugneaux and I built and tested the [viem PR](https://github.com/celo-org/viem/pull/6) that ended up being merged upstread to fix the bug, [the regression was fixed](https://github.com/celo-org/viem/pull/6#issuecomment-1790456705). 

Specifically, we built the viem on the PR branch, and used `npm link` to test the local build in my demo. The regression was fixed, which gave us confidence that the PR fixes the bug. 

A few hypotheses: 
- additional commits were added that broke the fix after we tested the local build (this can be checked on the PR)
- the local build we tested is not representative of the viem package that is published to NPM
- we are not updating viem version in the demo correctly (this can be tested with a clean repo clone and install)

**Comment by arthurgousset** [comment]
Ref: 
- https://github.com/celo-org/viem/pull/9
- https://github.com/wagmi-dev/viem/pull/1499

**Comment by arthurgousset** [comment]
Closing on behalf of @shazarre
